---
language: ruby

script: bundle exec rake

sudo: false

addons:
  apt:
    packages:
      - ragel

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ragel; fi

install:
  - bundle install --retry=3

rvm:
  - jruby
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
  - rbx

matrix:
  allow_failures:
    - rvm: rbx
      os: osx
  exclude:
    # Binaries for these rubies aren't available on OS X :<
    - rvm: 2.2
      os: osx
    - rvm: 2.3.1
      os: osx
    - rvm: jruby
      os: osx
  fast_finish: true

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    on_success: change
    on_failure: change

cache: bundler

os:
  - linux
  - osx
