---
language: ruby

script: bundle exec rake

sudo: false

addons:
  apt:
    packages:
      - ragel

install:
  - bundle install --retry=3

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    on_success: change
    on_failure: change

cache: bundler
