---
language: ruby

script: bundle exec rake

sudo: false

addons:
  apt:
    packages:
      - ragel

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ragel; fi

install:
  - bundle install --retry=3

rvm:
  - jruby
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - rbx

matrix:
  allow_failures:
    - rvm: rbx
  fast_finish: true

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    on_success: change
    on_failure: change

cache: bundler

os:
  - linux
  - osx
